"use strict";
let car = "subaru";
console.log("\t\tTest 1\nIs car == 'subaru'? I predict True.");
console.log(car == "subaru");
console.log("\t\tTest 2\nIs car != 'subaru'? I predict false.");
console.log(car != "subaru");
let num1 = 5;
console.log(`\t\tTest 3\nIs num1 <= 6, | I predict true \n and the result is "${num1 <= 6}"`);
console.log(`\t\tTest 4\nIs num1 > 6, | I predict false \n and the result is "${num1 > 6}"`);
let num2 = 5;
console.log(`\t\tTest 5\nIs num2 == 6, | I predict true \n and the result is "${num2 == 6}"`);
console.log(`\t\tTest 6\nIs num2 >= 6, | I predict false \n and the result is "${num2 >= 6}"`);
let num3 = "face";
console.log(`\t\tTest 7\nIs num3 == "face", | I predict true \n and the result is "${num3 == "face"}"`);
console.log(`\t\tTest 8\nIs num3 == "book", | I predict false \n and the result is "${num3 == "book"}"`);
let num4 = true;
console.log(`\t\tTest 9\nIs num4 == true, | I predict true \n and the result is "${num4 == true}"`);
console.log(`\t\tTest 10\nIs num4 != true, | I predict false \n and the result is "${num4 != true}"`);
